### ISSUE TITLE
"docker-compose up -d" command got an error

### ISSUE THREAD

**Issue by jxta** [yacchin1205/jupyter-for-infrastructure#1]
**I run the command several weeks ago and
I got the jupyter environment successfully, at that time.
However, I get the following error, now.**

  Failed building wheel for scandir
  Running setup.py clean for scandir
Successfully built terminado tornado pandocfilters MarkupSafe configparser html5lib simplegeneric functools32
Failed to build scandir
Installing collected packages: six, enum34, ipython-genutils, decorator, traitlets, MarkupSafe, jinja2, ptyprocess, singledispatch, certifi, backports-abc, tornado, terminado, pygments, pandocfilters, testpath, configparser, entrypoints, jupyter-core, functools32, jsonschema, nbformat, mistune, html5lib, bleach, nbconvert, pyzmq, jupyter-client, backports.shutil-get-terminal-size, scandir, pathlib2, pickleshare, simplegeneric, pexpect, wcwidth, prompt-toolkit, ipython, ipykernel, notebook, widgetsnbextension, ipywidgets, jupyter-console, qtconsole, jupyter
  Running setup.py install for scandir: started
    Running setup.py install for scandir: finished with status 'error'
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dXbDnF/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-USYY1D-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying scandir.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_scandir' extension
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Should  I fix something to run the command now?**

**Comment by yacchin1205** [comment]
Awesome! It seems that some dependencies of jupyter has been changed. I'll fix this.

**Comment by yacchin1205** [comment]
Fixed. Could you pull the latest code and try again? @jxta @naka999

**Comment by jxta** [comment]
It worked again. I appreciate that I can continue to work on my project.
